package com.jtrent238.orespawndzport;

import com.jtrent238.orespawndzport.blocks.BlockColor;
import com.jtrent238.orespawndzport.blocks.BlockMaterial;
import com.jtrent238.orespawndzport.blocks.BlockModFlower;
import com.jtrent238.orespawndzport.blocks.BlockModOre;
import com.jtrent238.orespawndzport.blocks.BlockToxicDirt;
import com.jtrent238.orespawndzport.blocks.BlockToxicLeaves;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.BlockStone;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;

public class BlockLoader {

	public static Block fossilbone;
	public static Block toxicdirt;
	public static Block toxicleaves;
	public static Block dargonstone1;
	public static Block dargonstone2;
	public static Block blockbloodstone;
	public static Block blockcopper;
	public static Block blockplatinum;
	public static Block blocksilver;
	public static Block blocksunstone;
	public static Block blocktin;
	
	public static Block orebloodstone;
	public static Block orecopper;
	public static Block oreplatinum;
	public static Block oresilver;
	public static Block oresunstone;
	public static Block oretin;
	
	public static Block oreannoyance;
	public static Block oreanteater;
	public static Block orebabydragon;
	public static Block orebabynope;
	public static Block orebeetle;
	public static Block orebird;
	public static Block orebuggerbat;
	public static Block orebulletbat;
	public static Block orebutterfly;
	public static Block orecatbat;
	public static Block orechamelion;
	public static Block orecockroach;
	public static Block orediamondbat;
	public static Block oredingbat;
	public static Block oredoomworm;
	public static Block oreelementdragon;
	public static Block oreexabat;
	public static Block orefatbat;
	public static Block oreflatbat;
	public static Block oreflattop;
	public static Block oregigabat;
	public static Block oregnatbat;
	public static Block oregoose;
	public static Block oregosling;
	public static Block oregrassmonster;
	public static Block orehammerheadshark;
	public static Block orehyena;
	public static Block oreickything;
	public static Block orekilobat;
	public static Block orelavalizard;
	public static Block orelavrov;
	public static Block orelazerlizard;
	public static Block orelightninglizard;
	public static Block orellama;
	public static Block oremegabat;
	public static Block oremermaid;
	public static Block oremoose;
	public static Block orenastysaurusprime;
	public static Block oreneedlenose;
	public static Block orenope;
	public static Block oreopossum;
	public static Block orepetabat;
	public static Block orepink;
	public static Block oreplatypus;
	public static Block oreputin;
	public static Block oreragingbull;
	public static Block oreratbat;
	public static Block orerattlesnake;
	public static Block oreredpanda;
	public static Block orereindeer;
	public static Block orerollyouchy;
	public static Block orerussian;
	public static Block oreschmoo;
	public static Block oreseaturtle;
	public static Block oreskeletorus;
	public static Block oreskinnything;
	public static Block oreskunk;
	public static Block oresloth;
	public static Block oresnail;
	public static Block oresparklemuffin;
	public static Block orespike;
	public static Block oresproing;
	public static Block oresquidguard;
	public static Block oreterabat;
	public static Block orethecount;
	public static Block oretigerseye;
	public static Block oretwodee;
	public static Block orev;
	public static Block orevampire;
	public static Block orevampiremoose;
	public static Block orevarmint;
	public static Block orevermin;
	public static Block orevixen;
	public static Block orewarthog;
	public static Block oreweasel;
	public static Block orewerewolf;
	public static Block orewhiner;
	public static Block orewoollymammoth;
	
	
	public static Block block_blue;
	public static Block block_brown;
	public static Block block_darkblue;
	public static Block block_darkbrown;
	public static Block block_darkgreen;
	public static Block block_darkgrey;
	public static Block block_darkorange;
	public static Block block_darkpurple;
	public static Block block_darkred;
	public static Block block_darkviolet;
	public static Block block_darkyellow;
	public static Block block_green;
	public static Block block_grey;
	public static Block block_lightblue;
	public static Block block_lightbrown;
	public static Block block_lightgreen;
	public static Block block_lightgrey;
	public static Block block_lightorange;
	public static Block block_lightpurple;
	public static Block block_lightred;
	public static Block block_lightviolet;
	public static Block block_lightyellow;
	public static Block block_orange;
	public static Block block_purple;
	public static Block block_red;
	public static Block block_violet;
	public static Block block_yellow;
	
	public static Block flower_pink;
	public static Block flower_purple;
	public static Block flower_red;
	public static Block flower_yellow;
	
	/**
	 * Load Blocks.
	 */
	public static void loadBlocks() {

		fossilbone = new BlockStone().setBlockName("fossilbone").setBlockTextureName("orespawndzport:fossilbone").setHardness(3F).setStepSound(Block.soundTypeStone).setCreativeTab(CreativeTabs.tabBlock);
		toxicdirt = new BlockToxicDirt(null, null).setBlockName("toxicdirt").setBlockTextureName("orespawndzport:darkdirt").setCreativeTab(CreativeTabs.tabBlock);
		toxicleaves = new BlockToxicLeaves().setBlockName("toxicleaves").setBlockTextureName("orespawndzport:darkleaves").setCreativeTab(CreativeTabs.tabBlock);
		dargonstone1 = new BlockStone().setBlockName("dargonstone1").setBlockTextureName("orespawndzport:dargonstone1").setCreativeTab(CreativeTabs.tabBlock);
		dargonstone2 = new BlockStone().setBlockName("dargonstone2").setBlockTextureName("orespawndzport:dargonstone2").setCreativeTab(CreativeTabs.tabBlock);
		
		blockbloodstone = new BlockMaterial(Material.iron).setBlockName("blockbloodstone").setBlockTextureName("orespawndzport:blockbloodstone").setCreativeTab(CreativeTabs.tabBlock);
		blockcopper = new BlockMaterial(Material.iron).setBlockName("blockcopper").setBlockTextureName("orespawndzport:blockcopper").setCreativeTab(CreativeTabs.tabBlock);
		blockplatinum = new BlockMaterial(Material.iron).setBlockName("blockplatinum").setBlockTextureName("orespawndzport:blockplatinum").setCreativeTab(CreativeTabs.tabBlock);
		blocksilver = new BlockMaterial(Material.iron).setBlockName("blocksilver").setBlockTextureName("orespawndzport:blocksilver").setCreativeTab(CreativeTabs.tabBlock);
		blocksunstone = new BlockMaterial(Material.iron).setBlockName("blocksunstone").setBlockTextureName("orespawndzport:blocksunstone").setCreativeTab(CreativeTabs.tabBlock);
		blocktin = new BlockMaterial(Material.iron).setBlockName("blocktin").setBlockTextureName("orespawndzport:blocktin").setCreativeTab(CreativeTabs.tabBlock);
		blockbloodstone = new BlockMaterial(Material.iron).setBlockName("blockbloodstone").setBlockTextureName("orespawndzport:blockbloodstone").setCreativeTab(CreativeTabs.tabBlock);
		
		orebloodstone = new BlockModOre(Material.rock).setBlockName("orebloodstone").setBlockTextureName("orespawndzport:orebloodstone").setCreativeTab(CreativeTabs.tabBlock);
		orecopper = new BlockModOre(Material.rock).setBlockName("orecopper").setBlockTextureName("orespawndzport:orecopper").setCreativeTab(CreativeTabs.tabBlock);
		oreplatinum = new BlockModOre(Material.rock).setBlockName("oreplatinum").setBlockTextureName("orespawndzport:oreplatinum").setCreativeTab(CreativeTabs.tabBlock);
		oresilver = new BlockModOre(Material.rock).setBlockName("oresilver").setBlockTextureName("orespawndzport:oresilver").setCreativeTab(CreativeTabs.tabBlock);
		oresunstone = new BlockModOre(Material.rock).setBlockName("oresunstone").setBlockTextureName("orespawndzport:oresunstone").setCreativeTab(CreativeTabs.tabBlock);
		oretin = new BlockModOre(Material.rock).setBlockName("oretin").setBlockTextureName("orespawndzport:oretin").setCreativeTab(CreativeTabs.tabBlock);

		oreannoyance = new BlockModOre(Material.rock).setBlockName("oreannoyance").setBlockTextureName("orespawndzport:oreannoyance").setCreativeTab(CreativeTabs.tabBlock);
		oreanteater = new BlockModOre(Material.rock).setBlockName("oreanteater").setBlockTextureName("orespawndzport:oreanteater").setCreativeTab(CreativeTabs.tabBlock);
		orebabydragon = new BlockModOre(Material.rock).setBlockName("orebabydragon").setBlockTextureName("orespawndzport:orebabydragon").setCreativeTab(CreativeTabs.tabBlock);
		orebabynope = new BlockModOre(Material.rock).setBlockName("orebabynope").setBlockTextureName("orespawndzport:orebabynope").setCreativeTab(CreativeTabs.tabBlock);
		orebeetle = new BlockModOre(Material.rock).setBlockName("orebeetle").setBlockTextureName("orespawndzport:orebeetle").setCreativeTab(CreativeTabs.tabBlock);
		orebird = new BlockModOre(Material.rock).setBlockName("orebird").setBlockTextureName("orespawndzport:orebird").setCreativeTab(CreativeTabs.tabBlock);
		orebuggerbat = new BlockModOre(Material.rock).setBlockName("orebuggerbat").setBlockTextureName("orespawndzport:orebuggerbat").setCreativeTab(CreativeTabs.tabBlock);
		orebulletbat = new BlockModOre(Material.rock).setBlockName("orebulletbat").setBlockTextureName("orespawndzport:orebulletbat").setCreativeTab(CreativeTabs.tabBlock);
		orebutterfly = new BlockModOre(Material.rock).setBlockName("orebutterfly").setBlockTextureName("orespawndzport:orebutterfly").setCreativeTab(CreativeTabs.tabBlock);
		orecatbat = new BlockModOre(Material.rock).setBlockName("orecatbat").setBlockTextureName("orespawndzport:orecatbat").setCreativeTab(CreativeTabs.tabBlock);
		orechamelion = new BlockModOre(Material.rock).setBlockName("orechamelion").setBlockTextureName("orespawndzport:orechamelion").setCreativeTab(CreativeTabs.tabBlock);
		orecockroach = new BlockModOre(Material.rock).setBlockName("orecockroach").setBlockTextureName("orespawndzport:orecockroach").setCreativeTab(CreativeTabs.tabBlock);
		orediamondbat = new BlockModOre(Material.rock).setBlockName("orediamondbat").setBlockTextureName("orespawndzport:orediamondbat").setCreativeTab(CreativeTabs.tabBlock);
		oredingbat = new BlockModOre(Material.rock).setBlockName("oredingbat").setBlockTextureName("orespawndzport:oredingbat").setCreativeTab(CreativeTabs.tabBlock);
		oredoomworm = new BlockModOre(Material.rock).setBlockName("oredoomworm").setBlockTextureName("orespawndzport:oredoomworm").setCreativeTab(CreativeTabs.tabBlock);
		oreelementdragon = new BlockModOre(Material.rock).setBlockName("oreelementdragon").setBlockTextureName("orespawndzport:oreelementdragon").setCreativeTab(CreativeTabs.tabBlock);
		oreexabat = new BlockModOre(Material.rock).setBlockName("oreexabat").setBlockTextureName("orespawndzport:oreexabat").setCreativeTab(CreativeTabs.tabBlock);
		orefatbat = new BlockModOre(Material.rock).setBlockName("orefatbat").setBlockTextureName("orespawndzport:orefatbat").setCreativeTab(CreativeTabs.tabBlock);
		oreflatbat = new BlockModOre(Material.rock).setBlockName("oreflatbat").setBlockTextureName("orespawndzport:oreflatbat").setCreativeTab(CreativeTabs.tabBlock);
		oreflattop = new BlockModOre(Material.rock).setBlockName("oreflattop").setBlockTextureName("orespawndzport:oreflattop").setCreativeTab(CreativeTabs.tabBlock);
		oregigabat = new BlockModOre(Material.rock).setBlockName("oregigabat").setBlockTextureName("orespawndzport:oregigabat").setCreativeTab(CreativeTabs.tabBlock);
		oregnatbat = new BlockModOre(Material.rock).setBlockName("oregnatbat").setBlockTextureName("orespawndzport:oregnatbat").setCreativeTab(CreativeTabs.tabBlock);
		oregoose = new BlockModOre(Material.rock).setBlockName("oregoose").setBlockTextureName("orespawndzport:oregoose").setCreativeTab(CreativeTabs.tabBlock);
		oregosling = new BlockModOre(Material.rock).setBlockName("oregosling").setBlockTextureName("orespawndzport:oregosling").setCreativeTab(CreativeTabs.tabBlock);
		oregrassmonster = new BlockModOre(Material.rock).setBlockName("oregrassmonster").setBlockTextureName("orespawndzport:oregrassmonster").setCreativeTab(CreativeTabs.tabBlock);
		orehammerheadshark = new BlockModOre(Material.rock).setBlockName("orehammerheadshark").setBlockTextureName("orespawndzport:orehammerheadshark").setCreativeTab(CreativeTabs.tabBlock);
		orehyena = new BlockModOre(Material.rock).setBlockName("orehyena").setBlockTextureName("orespawndzport:orehyena").setCreativeTab(CreativeTabs.tabBlock);
		oreickything = new BlockModOre(Material.rock).setBlockName("oreickything").setBlockTextureName("orespawndzport:oreickything").setCreativeTab(CreativeTabs.tabBlock);
		orekilobat = new BlockModOre(Material.rock).setBlockName("orekilobat").setBlockTextureName("orespawndzport:orekilobat").setCreativeTab(CreativeTabs.tabBlock);
		orelavalizard = new BlockModOre(Material.rock).setBlockName("orelavalizard").setBlockTextureName("orespawndzport:orelavalizard").setCreativeTab(CreativeTabs.tabBlock);
		orelavrov = new BlockModOre(Material.rock).setBlockName("orelavrov").setBlockTextureName("orespawndzport:orelavrov").setCreativeTab(CreativeTabs.tabBlock);
		orelazerlizard = new BlockModOre(Material.rock).setBlockName("orelazerlizard").setBlockTextureName("orespawndzport:orelazerlizard").setCreativeTab(CreativeTabs.tabBlock);
		orelightninglizard = new BlockModOre(Material.rock).setBlockName("orelightninglizard").setBlockTextureName("orespawndzport:orelightninglizard").setCreativeTab(CreativeTabs.tabBlock);
		orellama = new BlockModOre(Material.rock).setBlockName("orellama").setBlockTextureName("orespawndzport:orellama").setCreativeTab(CreativeTabs.tabBlock);
		oremegabat = new BlockModOre(Material.rock).setBlockName("oremegabat").setBlockTextureName("orespawndzport:oremegabat").setCreativeTab(CreativeTabs.tabBlock);
		oremermaid = new BlockModOre(Material.rock).setBlockName("oremermaid").setBlockTextureName("orespawndzport:oremermaid").setCreativeTab(CreativeTabs.tabBlock);
		oremoose = new BlockModOre(Material.rock).setBlockName("oremoose").setBlockTextureName("orespawndzport:oremoose").setCreativeTab(CreativeTabs.tabBlock);
		orenastysaurusprime = new BlockModOre(Material.rock).setBlockName("orenastysaurusprime").setBlockTextureName("orespawndzport:orenastysaurusprime").setCreativeTab(CreativeTabs.tabBlock);
		oreneedlenose = new BlockModOre(Material.rock).setBlockName("oreneedlenose").setBlockTextureName("orespawndzport:oreneedlenose").setCreativeTab(CreativeTabs.tabBlock);
		orenope = new BlockModOre(Material.rock).setBlockName("orenope").setBlockTextureName("orespawndzport:orenope").setCreativeTab(CreativeTabs.tabBlock);
		oreopossum = new BlockModOre(Material.rock).setBlockName("oreopossum").setBlockTextureName("orespawndzport:oreopossum").setCreativeTab(CreativeTabs.tabBlock);
		orepetabat = new BlockModOre(Material.rock).setBlockName("orepetabat").setBlockTextureName("orespawndzport:orepetabat").setCreativeTab(CreativeTabs.tabBlock);
		orepink = new BlockModOre(Material.rock).setBlockName("orepink").setBlockTextureName("orespawndzport:orepink").setCreativeTab(CreativeTabs.tabBlock);
		oreplatypus = new BlockModOre(Material.rock).setBlockName("oreplatypus").setBlockTextureName("orespawndzport:oreplatypus").setCreativeTab(CreativeTabs.tabBlock);
		oreputin = new BlockModOre(Material.rock).setBlockName("oreputin").setBlockTextureName("orespawndzport:oreputin").setCreativeTab(CreativeTabs.tabBlock);
		oreragingbull = new BlockModOre(Material.rock).setBlockName("oreragingbull").setBlockTextureName("orespawndzport:oreragingbull").setCreativeTab(CreativeTabs.tabBlock);
		oreratbat = new BlockModOre(Material.rock).setBlockName("oreratbat").setBlockTextureName("orespawndzport:oreratbat").setCreativeTab(CreativeTabs.tabBlock);
		orerattlesnake = new BlockModOre(Material.rock).setBlockName("orerattlesnake").setBlockTextureName("orespawndzport:orerattlesnake").setCreativeTab(CreativeTabs.tabBlock);
		oreredpanda = new BlockModOre(Material.rock).setBlockName("oreredpanda").setBlockTextureName("orespawndzport:oreredpanda").setCreativeTab(CreativeTabs.tabBlock);
		orereindeer = new BlockModOre(Material.rock).setBlockName("orereindeer").setBlockTextureName("orespawndzport:orereindeer").setCreativeTab(CreativeTabs.tabBlock);
		orerollyouchy = new BlockModOre(Material.rock).setBlockName("orerollyouchy").setBlockTextureName("orespawndzport:orerollyouchy").setCreativeTab(CreativeTabs.tabBlock);
		orerussian = new BlockModOre(Material.rock).setBlockName("orerussian").setBlockTextureName("orespawndzport:orerussian").setCreativeTab(CreativeTabs.tabBlock);
		oreschmoo = new BlockModOre(Material.rock).setBlockName("oreschmoo").setBlockTextureName("orespawndzport:oreschmoo").setCreativeTab(CreativeTabs.tabBlock);
		oreseaturtle = new BlockModOre(Material.rock).setBlockName("oreseaturtle").setBlockTextureName("orespawndzport:oreseaturtle").setCreativeTab(CreativeTabs.tabBlock);
		oreskeletorus = new BlockModOre(Material.rock).setBlockName("oreskeletorus").setBlockTextureName("orespawndzport:oreskeletorus").setCreativeTab(CreativeTabs.tabBlock);
		oreskinnything = new BlockModOre(Material.rock).setBlockName("oreskinnything").setBlockTextureName("orespawndzport:oreskinnything").setCreativeTab(CreativeTabs.tabBlock);
		oreskunk = new BlockModOre(Material.rock).setBlockName("oreskunk").setBlockTextureName("orespawndzport:oreskunk").setCreativeTab(CreativeTabs.tabBlock);
		oresloth = new BlockModOre(Material.rock).setBlockName("oresloth").setBlockTextureName("orespawndzport:oresloth").setCreativeTab(CreativeTabs.tabBlock);
		oresnail = new BlockModOre(Material.rock).setBlockName("oresnail").setBlockTextureName("orespawndzport:oresnail").setCreativeTab(CreativeTabs.tabBlock);
		oresparklemuffin = new BlockModOre(Material.rock).setBlockName("oresparklemuffin").setBlockTextureName("orespawndzport:oresparklemuffin").setCreativeTab(CreativeTabs.tabBlock);
		orespike = new BlockModOre(Material.rock).setBlockName("orespike").setBlockTextureName("orespawndzport:orespike").setCreativeTab(CreativeTabs.tabBlock);
		oresproing = new BlockModOre(Material.rock).setBlockName("oresproing").setBlockTextureName("orespawndzport:oresproing").setCreativeTab(CreativeTabs.tabBlock);
		oresquidguard = new BlockModOre(Material.rock).setBlockName("oresquidguard").setBlockTextureName("orespawndzport:oresquidguard").setCreativeTab(CreativeTabs.tabBlock);
		oreterabat = new BlockModOre(Material.rock).setBlockName("oreterabat").setBlockTextureName("orespawndzport:oreterabat").setCreativeTab(CreativeTabs.tabBlock);
		orethecount = new BlockModOre(Material.rock).setBlockName("orethecount").setBlockTextureName("orespawndzport:orethecount").setCreativeTab(CreativeTabs.tabBlock);
		oretigerseye = new BlockModOre(Material.rock).setBlockName("oretigerseye").setBlockTextureName("orespawndzport:oretigerseye").setCreativeTab(CreativeTabs.tabBlock);
		oretwodee = new BlockModOre(Material.rock).setBlockName("oretwodee").setBlockTextureName("orespawndzport:oretwodee").setCreativeTab(CreativeTabs.tabBlock);
		orev = new BlockModOre(Material.rock).setBlockName("orev").setBlockTextureName("orespawndzport:orev").setCreativeTab(CreativeTabs.tabBlock);
		orevampire = new BlockModOre(Material.rock).setBlockName("orevampire").setBlockTextureName("orespawndzport:orevampire").setCreativeTab(CreativeTabs.tabBlock);
		orevampiremoose = new BlockModOre(Material.rock).setBlockName("orevampiremoose").setBlockTextureName("orespawndzport:orevampiremoose").setCreativeTab(CreativeTabs.tabBlock);
		orevarmint = new BlockModOre(Material.rock).setBlockName("orevarmint").setBlockTextureName("orespawndzport:orevarmint").setCreativeTab(CreativeTabs.tabBlock);
		orevermin = new BlockModOre(Material.rock).setBlockName("orevermin").setBlockTextureName("orespawndzport:orevermin").setCreativeTab(CreativeTabs.tabBlock);
		orevixen = new BlockModOre(Material.rock).setBlockName("orevixen").setBlockTextureName("orespawndzport:orevixen").setCreativeTab(CreativeTabs.tabBlock);
		orewarthog = new BlockModOre(Material.rock).setBlockName("orewarthog").setBlockTextureName("orespawndzport:orewarthog").setCreativeTab(CreativeTabs.tabBlock);
		oreweasel = new BlockModOre(Material.rock).setBlockName("oreweasel").setBlockTextureName("orespawndzport:oreweasel").setCreativeTab(CreativeTabs.tabBlock);
		orewerewolf = new BlockModOre(Material.rock).setBlockName("orewerewolf").setBlockTextureName("orespawndzport:orewerewolf").setCreativeTab(CreativeTabs.tabBlock);
		orewhiner = new BlockModOre(Material.rock).setBlockName("orewhiner").setBlockTextureName("orespawndzport:orewhiner").setCreativeTab(CreativeTabs.tabBlock);
		orewoollymammoth = new BlockModOre(Material.rock).setBlockName("orewoollymammoth").setBlockTextureName("orespawndzport:orewoollymammoth").setCreativeTab(CreativeTabs.tabBlock);
		
		block_blue = new BlockColor(Material.rock).setBlockName("block_blue").setBlockTextureName("orespawndzport:block_blue").setCreativeTab(CreativeTabs.tabBlock);
		block_brown = new BlockColor(Material.rock).setBlockName("block_brown").setBlockTextureName("orespawndzport:block_brown").setCreativeTab(CreativeTabs.tabBlock);
		block_darkblue = new BlockColor(Material.rock).setBlockName("block_darkblue").setBlockTextureName("orespawndzport:block_darkblue").setCreativeTab(CreativeTabs.tabBlock);
		block_darkbrown = new BlockColor(Material.rock).setBlockName("block_darkbrown").setBlockTextureName("orespawndzport:block_darkbrown").setCreativeTab(CreativeTabs.tabBlock);
		block_darkgreen = new BlockColor(Material.rock).setBlockName("block_darkgreen").setBlockTextureName("orespawndzport:block_darkgreen").setCreativeTab(CreativeTabs.tabBlock);
		block_darkgrey = new BlockColor(Material.rock).setBlockName("block_darkgrey").setBlockTextureName("orespawndzport:block_darkgrey").setCreativeTab(CreativeTabs.tabBlock);
		block_darkorange = new BlockColor(Material.rock).setBlockName("block_darkorange").setBlockTextureName("orespawndzport:block_darkorange").setCreativeTab(CreativeTabs.tabBlock);
		block_darkpurple = new BlockColor(Material.rock).setBlockName("block_darkpurple").setBlockTextureName("orespawndzport:block_darkpurple").setCreativeTab(CreativeTabs.tabBlock);
		block_darkred = new BlockColor(Material.rock).setBlockName("block_darkred").setBlockTextureName("orespawndzport:block_darkred").setCreativeTab(CreativeTabs.tabBlock);
		block_darkviolet = new BlockColor(Material.rock).setBlockName("block_darkviolet").setBlockTextureName("orespawndzport:block_darkviolet").setCreativeTab(CreativeTabs.tabBlock);
		block_darkyellow = new BlockColor(Material.rock).setBlockName("block_darkyellow").setBlockTextureName("orespawndzport:block_darkyellow").setCreativeTab(CreativeTabs.tabBlock);
		block_green = new BlockColor(Material.rock).setBlockName("block_green").setBlockTextureName("orespawndzport:block_green").setCreativeTab(CreativeTabs.tabBlock);
		block_grey = new BlockColor(Material.rock).setBlockName("block_grey").setBlockTextureName("orespawndzport:block_grey").setCreativeTab(CreativeTabs.tabBlock);
		block_lightblue = new BlockColor(Material.rock).setBlockName("block_lightblue").setBlockTextureName("orespawndzport:oretin").setCreativeTab(CreativeTabs.tabBlock);
		block_lightbrown = new BlockColor(Material.rock).setBlockName("block_lightbrown").setBlockTextureName("orespawndzport:block_lightbrown").setCreativeTab(CreativeTabs.tabBlock);
		block_lightgreen = new BlockColor(Material.rock).setBlockName("block_lightgreen").setBlockTextureName("orespawndzport:block_lightgreen").setCreativeTab(CreativeTabs.tabBlock);
		block_lightgrey = new BlockColor(Material.rock).setBlockName("block_lightgrey").setBlockTextureName("orespawndzport:block_lightgrey").setCreativeTab(CreativeTabs.tabBlock);
		block_lightorange = new BlockColor(Material.rock).setBlockName("block_lightorange").setBlockTextureName("orespawndzport:block_lightorange").setCreativeTab(CreativeTabs.tabBlock);
		block_lightpurple = new BlockColor(Material.rock).setBlockName("block_lightpurple").setBlockTextureName("orespawndzport:block_lightpurple").setCreativeTab(CreativeTabs.tabBlock);
		block_lightred = new BlockColor(Material.rock).setBlockName("block_lightred").setBlockTextureName("orespawndzport:block_lightred").setCreativeTab(CreativeTabs.tabBlock);
		block_lightviolet = new BlockColor(Material.rock).setBlockName("block_lightviolet").setBlockTextureName("orespawndzport:block_lightviolet").setCreativeTab(CreativeTabs.tabBlock);
		block_lightyellow = new BlockColor(Material.rock).setBlockName("block_lightyellow").setBlockTextureName("orespawndzport:block_lightyellow").setCreativeTab(CreativeTabs.tabBlock);
		block_orange = new BlockColor(Material.rock).setBlockName("block_orange").setBlockTextureName("orespawndzport:block_orange").setCreativeTab(CreativeTabs.tabBlock);
		block_purple = new BlockColor(Material.rock).setBlockName("block_purple").setBlockTextureName("orespawndzport:block_purple").setCreativeTab(CreativeTabs.tabBlock);
		block_red = new BlockColor(Material.rock).setBlockName("block_red").setBlockTextureName("orespawndzport:block_red").setCreativeTab(CreativeTabs.tabBlock);
		block_violet = new BlockColor(Material.rock).setBlockName("block_violet").setBlockTextureName("orespawndzport:block_violet").setCreativeTab(CreativeTabs.tabBlock);
		block_yellow = new BlockColor(Material.rock).setBlockName("block_yellow").setBlockTextureName("orespawndzport:block_yellow").setCreativeTab(CreativeTabs.tabBlock);
		
		flower_pink = new BlockModFlower(0).setBlockName("flower_pink").setBlockTextureName("orespawndzport:" + BlockModFlower.field_149860_M).setCreativeTab(CreativeTabs.tabDecorations);
		flower_purple = new BlockModFlower(1).setBlockName("flower_purple").setBlockTextureName("orespawndzport:" + BlockModFlower.field_149860_M).setCreativeTab(CreativeTabs.tabDecorations);
		flower_red = new BlockModFlower(2).setBlockName("flower_red").setBlockTextureName("orespawndzport:" + BlockModFlower.field_149860_M).setCreativeTab(CreativeTabs.tabDecorations);
		flower_yellow = new BlockModFlower(3).setBlockName("flower_yellow").setBlockTextureName("orespawndzport:" + BlockModFlower.field_149860_M).setCreativeTab(CreativeTabs.tabDecorations);
		
		registerBlocks();
	}

	/**
	 * Register Blocks.
	 */
	private static void registerBlocks(){

		GameRegistry.registerBlock(fossilbone, "fossilbone");
		GameRegistry.registerBlock(toxicdirt, "toxicdirt");
		GameRegistry.registerBlock(toxicleaves, "toxicleaves");
		GameRegistry.registerBlock(dargonstone1, "dargonstone1");
		GameRegistry.registerBlock(dargonstone2, "dargonstone2");
		
		GameRegistry.registerBlock(blockbloodstone, "blockbloodstone");
		GameRegistry.registerBlock(blockcopper, "blockcopper");
		GameRegistry.registerBlock(blockplatinum, "blockplatinum");
		GameRegistry.registerBlock(blocksilver, "blocksilver");
		GameRegistry.registerBlock(blocksunstone, "blocksunstone");
		GameRegistry.registerBlock(blocktin, "blocktin");
		
		GameRegistry.registerBlock(orebloodstone, "orebloodstone");
		GameRegistry.registerBlock(orecopper, "orecopper");
		GameRegistry.registerBlock(oreplatinum, "oreplatinum");
		GameRegistry.registerBlock(oresilver, "oresilver");
		GameRegistry.registerBlock(oresunstone, "oresunstone");
		GameRegistry.registerBlock(oretin, "oretin");
		

		GameRegistry.registerBlock(oreannoyance, "oreannoyance");
		GameRegistry.registerBlock(oreanteater, "oreanteater");
		GameRegistry.registerBlock(orebabydragon, "orebabydragon");
		GameRegistry.registerBlock(orebabynope, "orebabynope");
		GameRegistry.registerBlock(orebeetle, "orebeetle");
		GameRegistry.registerBlock(orebird, "orebird");
		GameRegistry.registerBlock(orebuggerbat, "orebuggerbat");
		GameRegistry.registerBlock(orebulletbat, "orebulletbat");
		GameRegistry.registerBlock(orebutterfly, "orebutterfly");
		GameRegistry.registerBlock(orecatbat, "orecatbat");
		GameRegistry.registerBlock(orechamelion, "orechamelion");
		GameRegistry.registerBlock(orecockroach, "orecockroach");
		GameRegistry.registerBlock(orediamondbat, "orediamondbat");
		GameRegistry.registerBlock(oredingbat, "oredingbat");
		GameRegistry.registerBlock(oredoomworm, "oredoomworm");
		GameRegistry.registerBlock(oreelementdragon, "oreelementdragon");
		GameRegistry.registerBlock(oreexabat, "oreexabat");
		GameRegistry.registerBlock(orefatbat, "orefatbat");
		GameRegistry.registerBlock(oreflatbat, "oreflatbat");
		GameRegistry.registerBlock(oreflattop, "oreflattop");
		GameRegistry.registerBlock(oregigabat, "oregigabat");
		GameRegistry.registerBlock(oregnatbat, "oregnatbat");
		GameRegistry.registerBlock(oregoose, "oregoose");
		GameRegistry.registerBlock(oregosling, "oregosling");
		GameRegistry.registerBlock(oregrassmonster, "oregrassmonster");
		GameRegistry.registerBlock(orehammerheadshark, "orehammerheadshark");
		GameRegistry.registerBlock(orehyena, "orehyena");
		GameRegistry.registerBlock(oreickything, "oreickything");
		GameRegistry.registerBlock(orekilobat, "orekilobat");
		GameRegistry.registerBlock(orelavalizard, "orelavalizard");
		GameRegistry.registerBlock(orelavrov, "orelavrov");
		GameRegistry.registerBlock(orelazerlizard, "orelazerlizard");
		GameRegistry.registerBlock(orelightninglizard, "orelightninglizard");
		GameRegistry.registerBlock(orellama, "orellama");
		GameRegistry.registerBlock(oremegabat, "oremegabat");
		GameRegistry.registerBlock(oremermaid, "oremermaid");
		GameRegistry.registerBlock(oremoose, "oremoose");
		GameRegistry.registerBlock(orenastysaurusprime, "orenastysaurusprime");
		GameRegistry.registerBlock(oreneedlenose, "oreneedlenose");
		GameRegistry.registerBlock(orenope, "orenope");
		GameRegistry.registerBlock(oreopossum, "oreopossum");
		GameRegistry.registerBlock(orepetabat, "orepetabat");
		//GameRegistry.registerBlock(orepink, "orepink");
		GameRegistry.registerBlock(oreplatypus, "oreplatypus");
		GameRegistry.registerBlock(oreputin, "oreputin");
		GameRegistry.registerBlock(oreragingbull, "oreragingbull");
		GameRegistry.registerBlock(oreratbat, "oreratbat");
		GameRegistry.registerBlock(orerattlesnake, "orerattlesnake");
		GameRegistry.registerBlock(oreredpanda, "oreredpanda");
		GameRegistry.registerBlock(orereindeer, "orereindeer");
		GameRegistry.registerBlock(orerollyouchy, "orerollyouchy");
		GameRegistry.registerBlock(orerussian, "orerussian");
		GameRegistry.registerBlock(oreschmoo, "oreschmoo");
		GameRegistry.registerBlock(oreseaturtle, "oreseaturtle");
		GameRegistry.registerBlock(oreskeletorus, "oreskeletorus");
		GameRegistry.registerBlock(oreskinnything, "oreskinnything");
		GameRegistry.registerBlock(oreskunk, "oreskunk");
		GameRegistry.registerBlock(oresloth, "oresloth");
		GameRegistry.registerBlock(oresnail, "oresnail");
		GameRegistry.registerBlock(oresparklemuffin, "oresparklemuffin");
		GameRegistry.registerBlock(orespike, "orespike");
		GameRegistry.registerBlock(oresproing, "oresproing");
		GameRegistry.registerBlock(oresquidguard, "oresquidguard");
		GameRegistry.registerBlock(oreterabat, "oreterabat");
		GameRegistry.registerBlock(orethecount, "orethecount");
		//GameRegistry.registerBlock(oretigerseye, "oretigerseye");
		GameRegistry.registerBlock(oretwodee, "oretwodee");
		GameRegistry.registerBlock(orev, "orev");
		GameRegistry.registerBlock(orevampire, "orevampire");
		GameRegistry.registerBlock(orevampiremoose, "orevampiremoose");
		GameRegistry.registerBlock(orevarmint, "orevarmint");
		GameRegistry.registerBlock(orevermin, "orevermin");
		GameRegistry.registerBlock(orevixen, "orevixen");
		GameRegistry.registerBlock(orewarthog, "orewarthog");
		GameRegistry.registerBlock(oreweasel, "oreweasel");
		GameRegistry.registerBlock(orewerewolf, "orewerewolf");
		GameRegistry.registerBlock(orewhiner, "orewhiner");
		GameRegistry.registerBlock(orewoollymammoth, "orewoollymammoth");
		
		GameRegistry.registerBlock(block_blue, "block_blue");
		GameRegistry.registerBlock(block_brown, "block_brown");
		GameRegistry.registerBlock(block_darkblue, "block_darkblue");
		GameRegistry.registerBlock(block_darkbrown, "block_darkbrown");
		GameRegistry.registerBlock(block_darkgreen, "block_darkgreen");
		GameRegistry.registerBlock(block_darkgrey, "block_darkgrey");
		GameRegistry.registerBlock(block_darkorange, "block_darkorange");
		GameRegistry.registerBlock(block_darkpurple, "block_darkpurple");
		GameRegistry.registerBlock(block_darkred, "block_darkred");
		GameRegistry.registerBlock(block_darkviolet, "block_darkviolet");
		GameRegistry.registerBlock(block_darkyellow, "block_darkyellow");
		GameRegistry.registerBlock(block_green, "block_green");
		GameRegistry.registerBlock(block_grey, "block_grey");
		GameRegistry.registerBlock(block_lightblue, "block_lightblue");
		GameRegistry.registerBlock(block_lightbrown, "block_lightbrown");
		GameRegistry.registerBlock(block_lightgreen, "block_lightgreen");
		GameRegistry.registerBlock(block_lightgrey, "block_lightgrey");
		GameRegistry.registerBlock(block_lightorange, "block_lightorange");
		GameRegistry.registerBlock(block_lightpurple, "block_lightpurple");
		GameRegistry.registerBlock(block_lightred, "block_lightred");
		GameRegistry.registerBlock(block_lightviolet, "block_lightviolet");
		GameRegistry.registerBlock(block_lightyellow, "block_lightyellow");
		GameRegistry.registerBlock(block_orange, "block_orange");
		GameRegistry.registerBlock(block_purple, "block_purple");
		GameRegistry.registerBlock(block_red, "block_red");
		GameRegistry.registerBlock(block_violet, "block_violet");
		GameRegistry.registerBlock(block_yellow, "block_yellow");
		
		GameRegistry.registerBlock(flower_pink, "flower_pink");
		GameRegistry.registerBlock(flower_purple, "flower_purple");
		GameRegistry.registerBlock(flower_red, "flower_red");
		GameRegistry.registerBlock(flower_yellow, "flower_yellow");
		
	}
	
	
}
